# Generated by Django 6.0.6 on 2026-06-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True, verbose_name='Kategoriya nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(null=True, unique=True, verbose_name='Foydalanuvchi Telegram ID')),
                ('username', models.CharField(max_length=50, null=True, verbose_name='Foydalanuvchi Username')),
                ('user_full_name', models.CharField(max_length=25, null=True, verbose_name='Foydalanuvchi ism familiyasi')),
                ('phone_number', models.CharField(blank=True, max_length=18, verbose_name='Foydalanuvchi raqami')),
                ('language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telegram Tili')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
    ]
